# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 49ea7aad933eeb3d8eed194eefeeeee178daeb297f1efe34640c8e7a09ea4d05864df1a85777ab163d4bad3792f9464da4be2800016208cd963d91309074e335

test:
  secret_key_base: 273c9b6b7ba66bfdc0c162cb78443c7ea0b0b48a77d4c0be3dd5fb0d0665438a146adfd773a21b1043bcef9b9b2ebb178f5c68bc8ef8ec1f57af0478f8c2da56

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
